CREATE TABLE `bid_opportunities` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`source` text NOT NULL,
	`stage` text NOT NULL,
	`input_type` text NOT NULL,
	`raw_input` text NOT NULL,
	`extracted_requirements` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`bit_decision` text DEFAULT 'pending' NOT NULL,
	`bit_decision_data` text,
	`alternative_recommendation` text,
	`assigned_business_line_id` text,
	`assigned_bl_notified_at` integer,
	`extended_evaluation` text,
	`assigned_team` text,
	`team_notified_at` integer,
	`quick_scan_id` text,
	`deep_migration_analysis_id` text,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
