-- Vector Indexes for pgvector
--
-- NOTE:
-- pgvector (as of pg16 + current pgvector releases) cannot build `ivfflat` or `hnsw`
-- indexes for vectors with > 2000 dimensions. This project currently uses vector(3072)
-- (text-embedding-3-large), so we only ensure the extension exists here.
--
-- If you switch embeddings to <= 2000 dimensions (e.g. vector(1536)), you can re-enable
-- the ANN index statements below.
--
-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- --- ANN index templates (only valid for <= 2000 dimensions) ---
-- CREATE INDEX IF NOT EXISTS deal_embeddings_embedding_idx
-- ON deal_embeddings USING ivfflat (embedding vector_cosine_ops)
-- WITH (lists = 100);
--
-- CREATE INDEX IF NOT EXISTS raw_chunks_embedding_idx
-- ON raw_chunks USING ivfflat (embedding vector_cosine_ops)
-- WITH (lists = 50);
--
-- CREATE INDEX IF NOT EXISTS pre_qualifications_embedding_idx
-- ON pre_qualifications USING ivfflat (description_embedding vector_cosine_ops)
-- WITH (lists = 50);
