import { and, eq } from 'drizzle-orm';
import { NextResponse } from 'next/server';

import { getAgentResult, hasExpertAgentResults } from '@/lib/agents/expert-agents';
import type { ManagementSummary } from '@/lib/agents/expert-agents/summary-schema';
import { auth } from '@/lib/auth';
import { db } from '@/lib/db';
import { dealEmbeddings, preQualifications } from '@/lib/db/schema';

/**
 * Dashboard Section Highlights
 * Cached highlights generated by the summary agent
 */
export interface SectionHighlight {
  sectionId: string;
  sectionTitle: string;
  highlights: string[];
  confidence?: number;
  status: 'available' | 'pending' | 'no_data';
}

/**
 * BU Routing Recommendation
 */
export interface BURoutingRecommendation {
  recommendedBusinessUnit: string | null;
  confidence: number | null;
  reasoning: string | null;
}

/**
 * Dashboard Summary Response
 */
export interface DashboardSummaryResponse {
  managementSummary: ManagementSummary | null;
  sectionHighlights: SectionHighlight[];
  buRouting: BURoutingRecommendation;
  processingStatus: {
    isProcessing: boolean;
    currentStep?: string;
  };
}

// Section IDs mapped to their display titles
const SECTION_CONFIG: Record<string, { title: string; group: string }> = {
  facts: { title: 'Key Facts', group: 'Übersicht' },
  budget: { title: 'Budget', group: 'Ausschreibung' },
  timing: { title: 'Zeitplan / Verfahren', group: 'Ausschreibung' },
  contracts: { title: 'Verträge', group: 'Ausschreibung' },
  deliverables: { title: 'Leistungsumfang', group: 'Ausschreibung' },
  references: { title: 'Referenzen', group: 'Ausschreibung' },
  'award-criteria': { title: 'Zuschlagskriterien', group: 'Ausschreibung' },
  'offer-structure': { title: 'Angebotsstruktur', group: 'Ausschreibung' },
};

/**
 * Fetch section highlights from dealEmbeddings
 */
async function getSectionHighlights(preQualificationId: string): Promise<SectionHighlight[]> {
  const highlights: SectionHighlight[] = [];

  // Get all dashboard highlights from dealEmbeddings
  const storedHighlights = await db.query.dealEmbeddings.findMany({
    where: and(
      eq(dealEmbeddings.preQualificationId, preQualificationId),
      eq(dealEmbeddings.chunkType, 'dashboard_highlight')
    ),
  });

  // Build highlights map
  const highlightsMap = new Map<string, { highlights: string[]; confidence: number }>();
  for (const row of storedHighlights) {
    try {
      const metadata = row.metadata ? JSON.parse(row.metadata) : {};
      const sectionId = metadata.sectionId;
      if (sectionId && row.content) {
        const parsed = JSON.parse(row.content);
        highlightsMap.set(sectionId, {
          highlights: Array.isArray(parsed) ? parsed : [],
          confidence: row.confidence ?? 50,
        });
      }
    } catch {
      // Skip malformed entries
    }
  }

  // Build response for all configured sections
  for (const [sectionId, config] of Object.entries(SECTION_CONFIG)) {
    const stored = highlightsMap.get(sectionId);
    if (stored && stored.highlights.length > 0) {
      highlights.push({
        sectionId,
        sectionTitle: config.title,
        highlights: stored.highlights.slice(0, 3), // Max 3 highlights
        confidence: stored.confidence,
        status: 'available',
      });
    } else {
      highlights.push({
        sectionId,
        sectionTitle: config.title,
        highlights: [],
        status: 'pending',
      });
    }
  }

  return highlights;
}

/**
 * GET /api/pre-qualifications/[id]/dashboard-summary
 *
 * Returns aggregated dashboard data:
 * - Management Summary (from summary_expert agent)
 * - Section Highlights (Top-3 Key Facts per section)
 * - BU Routing Recommendation
 * - Processing Status
 */
export async function GET(_request: Request, context: { params: Promise<{ id: string }> }) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id: preQualificationId } = await context.params;

    // Verify ownership and get preQualification with quickScan
    const preQualification = await db.query.preQualifications.findFirst({
      where: and(
        eq(preQualifications.id, preQualificationId),
        eq(preQualifications.userId, session.user.id)
      ),
      with: {
        quickScan: true,
      },
    });

    if (!preQualification) {
      return NextResponse.json({ error: 'Not found' }, { status: 404 });
    }

    // Get Management Summary from expert agent results
    let managementSummary: ManagementSummary | null = null;
    const hasResults = await hasExpertAgentResults(preQualificationId);
    if (hasResults) {
      const summaryResult = await getAgentResult(preQualificationId, 'summary_expert');
      if (summaryResult?.metadata) {
        managementSummary = summaryResult.metadata as unknown as ManagementSummary;
      }
    }

    // Get Section Highlights
    const sectionHighlights = await getSectionHighlights(preQualificationId);

    // Get BU Routing from quickScan
    const quickScan = preQualification.quickScan;
    const buRouting: BURoutingRecommendation = {
      recommendedBusinessUnit: quickScan?.recommendedBusinessUnit ?? null,
      confidence: quickScan?.confidence ?? null,
      reasoning: quickScan?.reasoning ?? null,
    };

    // Determine processing status
    const processingStatuses = new Set([
      'processing',
      'extracting',
      'duplicate_checking',
      'quick_scanning',
      'timeline_estimating',
      'evaluating',
    ]);
    const isProcessing = processingStatuses.has(preQualification.status);

    const response: DashboardSummaryResponse = {
      managementSummary,
      sectionHighlights,
      buRouting,
      processingStatus: {
        isProcessing,
        currentStep: isProcessing ? preQualification.status : undefined,
      },
    };

    return NextResponse.json(response);
  } catch (error) {
    console.error('[Dashboard Summary API] Error:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}
